### ISSUE TITLE
The specified time range is empty

### ISSUE THREAD

**Issue by matthanna** [richardfearn/mythcal#18]
cd /mythtv/scripts/mythcal && ./mythcal -v

Traceback (most recent call last):
  File "./mythcal", line 309, in <module>
    service.events().insert(calendarId = settings.calendar.id, body=event).execute()
  File "/usr/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/apiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
apiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/{email account}/events?alt=json returned "The specified time range is empty.">

**Comment by richardfearn** [comment]
Does this happen every time?

What OS are you running?

What version of the Python Google API are you using?

(Let me know if you need a hand finding this information out)

**Comment by di3orlive** [comment]
just all timezone

**Comment by richardfearn** [comment]
Could have been because the end time was the same as, or before, the start time.

https://stackoverflow.com/q/10891425/200609
